trigger:
  branches:
    include:
      - main  # Trigger on push to main branch

pool: 
  name: 'PoolForEC2'
  vmImage: 'ubuntu-latest'

variables:
  MY_DOCKER_IMAGE: 'simple-web-app'  # My app name
  EC2_USER: 'ec2-user'  # User of my ec2
  EC2_HOST: '54.73.223.124'  # my EC2's public ip
  SSH_KEY: $(EC2_SSH_KEY)  # Private key of ec2 Securely store in Azure DevOps secrets

stages:
- stage: Build
  jobs:
  - job: BuildingDockerFileAndPushToPipelineWorkSpace
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        dockerfile: 'dockerfile'
        repository: $(MY_DOCKER_IMAGE)
        tags: web_app

    - script: |
        docker save -o $(Pipeline.Workspace)/webapp.tar $(MY_DOCKER_IMAGE):web_app
      displayName: 'Save Docker image to tar'

- stage: Deploy
  jobs:
  - job: DeployToEC2
    steps:

    - task: SSH@0
      inputs:
        sshEndpoint: 'MyEC2SSHConnection'
        runOptions: 'inline'
        inline: |
          docker load -i $(Pipeline.Workspace)/webapp.tar
          docker run -d -p 5000:5000 --name my-web-app $(MY_DOCKER_IMAGE):web_app
