trigger:
  branches:
    include:
      - main  # Trigger on push to main branch

pool: 
  name: 'PoolForEC2'
  vmImage: 'ubuntu-latest'

variables:
  MY_DOCKER_IMAGE: 'simple-web-app'  # My app name

stages:
- stage: Build
  jobs:
  - job: BuildingDockerFileAndPushToPipelineWorkSpace
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        dockerfile: 'dockerfile'
        repository: $(MY_DOCKER_IMAGE)
        tags: web_app

    - script: |
        docker save -o $(Pipeline.Workspace)/webapp.tar $(MY_DOCKER_IMAGE):web_app
      displayName: 'Save Docker image to tar'

- stage: Deploy
  jobs:
  - job: DeployToEC2
    steps:

    - task: SSH@0
      inputs:
        sshEndpoint: 'MyEC2SSHConnection'
        runOptions: 'inline'
        inline: |
          docker load -i $(Pipeline.Workspace)/webapp.tar
          docker stop my-web-app || true
          docker rm my-web-app || true
          docker run -d -p 80:80 --name my-web-app $(MY_DOCKER_IMAGE):web_app
